-- TABLA USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    EMAIL VARCHAR2(100),
    PASSWD VARCHAR2(50),
    SALDO NUMBER
);

CREATE SEQUENCE SEQ_USUARIO;

-- TABLA GALGOS
CREATE TABLE GALGOS (
    ID_GALGO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    DORSAL NUMBER,
    COLOR VARCHAR2(50),
    GANANCIA NUMBER,
    ACELERACION NUMBER,
    VELOCIDAD NUMBER,
    EXPERIENCIA NUMBER,
    AVANCE NUMBER
);

-- TABLA CARRERAS
CREATE TABLE CARRERAS (
    ID_CARRERA NUMBER PRIMARY KEY,
    CIUDAD VARCHAR2(50),
    HORA VARCHAR2(20),
    PARTICIPANTES CLOB,
    ESTADO VARCHAR2(5),
    CLASIFICACION CLOB
);