--TABLA USUARIOS
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, EMAIL, PASSWD, SALDO) VALUES (1, 'Usuario1', 'usuario1@gmail.com', 'clave1', 0);
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, EMAIL, PASSWD, SALDO) VALUES (2, 'Usuario2', 'usuario2@gmail.com', 'clave2', 0);
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, EMAIL, PASSWD, SALDO) VALUES (3, 'Usuario3', 'usuario3@gmail.com', 'clave3', 0);
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, EMAIL, PASSWD, SALDO) VALUES (4, 'Usuario4', 'usuario4@gmail.com', 'clave4', 0);


--TABLA GALGOS
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (1, 'Sparky', 2, 'Rojo', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (2, 'Luna', 3, 'Azul', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (3, 'Bolt', 4, 'Verde', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (4, 'Cocoa', 5, 'Amarillo', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (5, 'Shadow', 6, 'Negro', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (6, 'Snowflake', 7, 'Blanco', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (7, 'Rocky', 8, 'Rojo', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (8, 'Sky', 9, 'Azul', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (9, 'Misty', 10, 'Verde', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (10, 'Sunny', 11, 'Amarillo', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (11, 'Midnight', 12, 'Negro', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (12, 'Cloud', 13, 'Blanco', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (13, 'Blaze', 14, 'Rojo', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (14, 'Daisy', 15, 'Azul', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (15, 'Rusty', 16, 'Verde', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (16, 'Frosty', 17, 'Amarillo', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (17, 'Thunder', 18, 'Negro', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (18, 'Pearl', 19, 'Blanco', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (19, 'Rocco', 20, 'Rojo', 0, NULL, NULL, NULL, 0);
INSERT INTO GALGOS (ID_GALGO, NOMBRE, DORSAL, COLOR, GANANCIA, ACELERACION, VELOCIDAD, EXPERIENCIA, AVANCE) VALUES (20, 'Star', 21, 'Azul', 0, NULL, NULL, NULL, 0);

--TABLA CARRERAS
INSERT INTO CARRERAS (ID_CARRERA, CIUDAD, HORA, PARTICIPANTES, ESTADO, CLASIFICACION) VALUES (1, 'Madrid', '10:00 AM', EMPTY_CLOB(), 0, EMPTY_CLOB());
INSERT INTO CARRERAS (ID_CARRERA, CIUDAD, HORA, PARTICIPANTES, ESTADO, CLASIFICACION) VALUES (2, 'Berlin', '11:30 AM', EMPTY_CLOB(), 0, EMPTY_CLOB());
INSERT INTO CARRERAS (ID_CARRERA, CIUDAD, HORA, PARTICIPANTES, ESTADO, CLASIFICACION) VALUES (3, 'Londres', '13:00 PM', EMPTY_CLOB(), 0, EMPTY_CLOB());
INSERT INTO CARRERAS (ID_CARRERA, CIUDAD, HORA, PARTICIPANTES, ESTADO, CLASIFICACION) VALUES (4, 'New York', '02:30 PM', EMPTY_CLOB(), 0, EMPTY_CLOB());
INSERT INTO CARRERAS (ID_CARRERA, CIUDAD, HORA, PARTICIPANTES, ESTADO, CLASIFICACION) VALUES (5, 'Moscú', '16:00 PM', EMPTY_CLOB(), 0, EMPTY_CLOB());
INSERT INTO CARRERAS (ID_CARRERA, CIUDAD, HORA, PARTICIPANTES, ESTADO, CLASIFICACION) VALUES (6, 'Tokio', '17:30 PM', EMPTY_CLOB(), 0, EMPTY_CLOB());
INSERT INTO CARRERAS (ID_CARRERA, CIUDAD, HORA, PARTICIPANTES, ESTADO, CLASIFICACION) VALUES (7, 'París', '19:00 PM', EMPTY_CLOB(), 0, EMPTY_CLOB());
INSERT INTO CARRERAS (ID_CARRERA, CIUDAD, HORA, PARTICIPANTES, ESTADO, CLASIFICACION) VALUES (8, 'Munich', '08:30 PM', EMPTY_CLOB(), 0, EMPTY_CLOB());
INSERT INTO CARRERAS (ID_CARRERA, CIUDAD, HORA, PARTICIPANTES, ESTADO, CLASIFICACION) VALUES (9, 'Toronto', '22:00 PM', EMPTY_CLOB(), 0, EMPTY_CLOB());
INSERT INTO CARRERAS (ID_CARRERA, CIUDAD, HORA, PARTICIPANTES, ESTADO, CLASIFICACION) VALUES (10, 'Miami', '23:30 PM', EMPTY_CLOB(), 0, EMPTY_CLOB());

